apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.pv.name }}
  namespace: {{ .Values.namespace }}
spec:
  capacity:
    storage: {{ .Values.pv.capacity }}
  accessModes:
    - {{ .Values.pv.accessMode }}
  hostPath:
    path: {{ .Values.pv.hostPath }}  # Ruta donde se almacenan los archivos

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.pvc.name }}
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - {{ .Values.pvc.accessMode }}
  resources:
    requests:
      storage: {{ .Values.pvc.storageRequest }}
